services:
  marquez:
    image: marquezproject/marquez:latest
    ports:
      - "5002:5000"
      - "5001:5001"
    volumes:
      - ./docker/wait-for-it.sh:/usr/src/app/wait-for-it.sh
    depends_on:
      - postgres
    environment:
      - MARQUEZ_DB_USER=marquez
      - MARQUEZ_DB_PASSWORD=marquez_pass
      - MARQUEZ_DB_HOST=postgres
      - MARQUEZ_DB_PORT=5432
      - MARQUEZ_DB_NAME=marquez_db
      - MARQUEZ_NAMESPACE=default
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--", "./entrypoint.sh"]

  marquez_web:
    image: marquezproject/marquez-web:latest
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
      - REACT_APP_ADVANCED_SEARCH=false
      - WEB_PORT=3000
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - marquez

  postgres:
    image: bitnami/postgresql:16
    container_name: postgres
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez_pass
      - MARQUEZ_DB=marquez_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh


  redis:
    image: bitnami/redis:6.0.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes